name: build

on:
    push:
        branches: [main]
        paths-ignore: [README.md]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build and test
              run: make test-all
